<template>
    <div>
        <Html>
            <Head>
                <Title>Medusa + Nuxt App</Title>
                <Meta name="description" content="Generated by npx nuxi init" />
                <Link rel="icon" href="/favicon.ico" />
            </Head>
        </Html>
        <NuxtLayout>
            <NuxtPage />
        </NuxtLayout>
    </div>
</template>

<script setup lang="ts">
import { useStore } from '@/stores/useStore'

const store = useStore();
const { initialize } = store;

await useAsyncData("init-medusa", async () => {
    await initialize();
});
</script>

